services:
  flask_db:
    image: postgres:latest
    container_name: bdp_postgres
    env_file:
      - .env.postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}" ]
      interval: 10s
      timeout: 5s
      retries: 5

  flask_app:
    build: ./flask_app
    container_name: flask_app
    env_file:
      - .env.flask
    volumes:
      - ./StockEtablissement.csv:/docker-entrypoint-initdb.d/StockEtablissement.csv:ro
    ports:
      - "5000:5000"
    networks:
      - backend
    depends_on:
      flask_db:
        condition: service_healthy


networks:
  backend:
    driver: bridge

volumes:
  postgres_data:
    driver: local
