name: Python application

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.11.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.11.10"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        # Specify the correct path to requirements.txt inside flask_app
        if [ -f flask_app/requirements.txt ]; then pip install -r flask_app/requirements.txt; fi

    - name: Lint with flake8
      run: |
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

    - name: Run tests with pytest
      run: |
        # Run tests located in the flask_app/tests directory
        pytest flask_app/tests --maxfail=3 --disable-warnings
